version: "3"

services:
  bitcoind:
    container_name: bitcoind
    restart: always
    image: btcpayserver/bitcoin:24.0.1-1
    ports:
      - 18443:18443
      - 18444:18444
      - 18445:18445
    
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_EXTRA_ARGS: |
        server=1
        debug=1
        rpcbind=bitcoind
        rpcport=18443
        rpcauth=foo:7d9ba5ae63c3d4dc30583ff4fe65a67e$$9e3634e81c11659e3de036d0bf88f89cd169c1039e6e09607562d54765c649cc
        rpcallowip=172.22.0.2/16
    
    volumes:
    - "bitcoind_data:/data"

  nbxplorer:
    container_name: nbxplorer
    restart: always
    image: "nicolasdorier/nbxplorer:2.3.57"
    # image: "nicolasdorier/nbxplorer:2.1.10"
    expose:
      - "32838"
    environment:
      NBXPLORER_NETWORK: regtest 
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_CHAINS: btc
      NBXPLORER_SIGNALFILEDIR: /datadir
      NBXPLORER_BTCRPCURL: bitcoind:18443
      NBXPLORER_BTCNODEENDPOINT: bitcoind:18444
      NBXPLORER_BTCRPCUSER: foo
      NBXPLORER_POSTGRES: User ID=postgres;Application Name=btcpayserverregtest;Include Error Detail=true;Host=postgres;Port=5432;
      NBXPLORER_BTCRPCPASSWORD: qDDZdeQ5vw9XXFeVnXT4PZ--tGN2xNjjR4nrtyszZx0=

# postgres=User ID=btcpay;Password=urpassword;Application Name=btcpayserver;Host=localhost;Port=5432;Database=btcpay;

      # DbPassword: qDDZdeQ5vw9XXFeVnXT4PZ--tGN2xNjjR4nrtyszZx0=
      # NBXPLORER_POSTGRES: User ID=postgres;Application Name=payserverdb;Include Error Detail=true;Host=localhost;Port=5432
    command: --noauth
    
    volumes:
      - "bitcoind_data:/root/.bitcoin"
      - "nbxplorer_data:/datadir"
    links:
      - bitcoind

  btcpay:
    container_name: btcpay
    restart: always
    image: "btcpayserver/btcpayserver:1.7.5"

    # image: "btcpayserver/btcpayserver:1.0.3.118"
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Database=btcpayserverregtest
      BTCPAY_NETWORK: regtest
      BTCPAY_ROOTPATH: /
      BTCPAY_CHAINS: btc
      BTCPAY_SOCKSENDPOINT: tor:9050
      BTCPAY_TORRCFILE: /usr/local/etc/tor/torrc-2
      BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838
      HIDDENSERVICE_NAME: BTCPayServer
    volumes:
      - "btcpay_data:/datadir"
      - "nbxplorer_data:/root/.nbxplorer"
      - "torrc_data:/usr/local/etc/tor/"
      - "torservice_data:/var/lib/tor/hidden_services"
    links:
     - nbxplorer
     - postgres
     - tor
  


  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    # image: postgres:9.6.5
    expose:
      - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      # POSTGRES_PASSWORD: password
      
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      
  tor: 
    container_name: tor
    restart: always
    image: btcpayserver/tor:0.4.7.10
    # image: btcpayserver/tor:0.3.5.8
    expose:
      - "9050"
    environment:
      TOR_PASSWORD: btcpayserver
      TOR_ADDITIONAL_CONFIG: /usr/local/etc/tor/torrc-2
      TOR_EXTRA_ARGS: |
        CookieAuthentication 1
    volumes:
      - "torrc_data:/usr/local/etc/tor"
      - "torservice_data:/var/lib/tor/hidden_services"
   
  tor-gen:
    container_name: tor-gen
    restart: always
    image: btcpayserver/docker-gen:0.7.5
    entrypoint: /usr/local/bin/docker-gen -notify-sighup tor -watch -wait 5s:30s /etc/docker-gen/templates/torrc.tmpl /usr/local/etc/tor/torrc-2
    volumes:
        - "/var/run/docker.sock:/tmp/docker.sock:ro"
        - "./torrc.tmpl:/etc/docker-gen/templates/torrc.tmpl:ro"
        - "torrc_data:/usr/local/etc/tor"

#  docker run -p 8069:8069 --name odoo --link db:db -t odoo
#   odoo:
#     container_name: odoo
#     restart: always
#     image: odoo:latest
#     ports:
#       - "8069:8069"
#     links:
#       - db

#  # docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo -e POSTGRES_DB=postgres --name db postgres:13

#   db:
#     container_name: db
#     restart: always
#     image: postgres:13
#     # image: postgres:9.6.5
#     environment:
#       POSTGRES_USER: odoo
#       POSTGRES_PASSWORD: odoo
#       POSTGRES_DB: postgres

#     expose:
#       - "5432"
   
    
volumes:
  bitcoind_data:
  nbxplorer_data:
  btcpay_data:
  postgres_data:

  torrc_data:
  torservice_data:

networks: {}

# /var/lib/docker/volumes/btcpayserver_demo_torservice_data/_data/BTCPayServer/hostname